const fs=require('fs'),assert=require('assert'),{spawnSync,spawn}=require('child_process'),{randomUUID}=require('crypto');
if(!process.env.FINPULSE_TEST_DATABASE_URL || process.env.FINPULSE_DISPOSABLE_DB!=='true') throw Error('Requires explicitly disposable test database');
const url=process.env.FINPULSE_TEST_DATABASE_URL;
if(new URL(url).pathname !== '/finpulse_test')throw Error('Disposable database must be named finpulse_test');
if(!/^postgres(?:ql)?:\/\/(?:[^@]+@)?(?:localhost|127\.0\.0\.1)(?::\d+)?\//.test(url))throw Error('CI test URL must be localhost');
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const lit=x=>"'"+String(x).replaceAll("'","''")+"'";
function sql(q){const r=spawnSync('psql',[url,'-X','-v','ON_ERROR_STOP=1','-qAt'],{input:q,encoding:'utf8'});if(r.status!==0)throw Error(r.stderr.trim());return r.stdout.trim();}
function asyncSql(q){return new Promise((res,rej)=>{const p=spawn('psql',[url,'-X','-v','ON_ERROR_STOP=1','-qAt']);let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',rej);p.on('close',c=>c===0?res(out.trim()):rej(Error(err)));p.stdin.end(q);});}
function query(id,kind,payload,actor=A,role='authenticated'){return `set role ${role}; set request.jwt.claim.sub=${lit(actor||'')}; select public.fp_mutate_transaction(${lit(id)}::uuid,${lit(kind)},${lit(JSON.stringify(payload))}::jsonb);`;}
const call=(id,kind,payload,actor=A,role='authenticated')=>JSON.parse(sql(query(id,kind,payload,actor,role)));
const record=(loan,extra=0,monthly=true)=>({loan_id:loan,extra,include_monthly:monthly,date:'2026-10-10'});
const balance=id=>Number(sql(`select balance from public.transactions where id=${lit(id)}`));
const count=()=>Number(sql('select count(*) from public.transactions'));
const receipts=()=>Number(sql('select count(*) from finpulse_private.operations'));
function loan(bal=5000,apr=12,min=200,actor=A,description='Test Car Loan'){const id=randomUUID();sql(`insert into public.transactions(id,user_id,type,description,amount,min_payment,balance,original_balance,apr,date,anchor_date,recurring,frequency) values(${lit(id)},${lit(actor)},'loan',${lit(description)},${min},${min},${bal},${bal},${apr},'2026-10-10','2026-10-10',true,'monthly');`);return id;}
function reset(){sql('truncate public.transactions,public.bill_paid_marks,finpulse_private.operations;');}
function fail(fn,pattern){assert.throws(fn,pattern);}
let pass=0,failed=0;
async function test(name,fn){try{reset();await fn();pass++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' -> '+e.message);}}
(async()=>{
 sql(fs.readFileSync('phase1/database/fixture.sql','utf8'));
 sql(fs.readFileSync('database/atomic-loan-operations.sql','utf8'));
 sql(fs.readFileSync('database/bill-paid-marks.sql','utf8'));
 sql(fs.readFileSync('database/owner-policy-performance.sql','utf8'));
 sql(fs.readFileSync('database/financial-goals.sql','utf8'));
 await test('goals persist exact amounts with owner isolation',()=>{
   const id=randomUUID();sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};insert into public.financial_goals(id,user_id,name,target_amount,saved_amount,monthly_amount) values(${lit(id)},${lit(A)},'Trip',1000,250.50,100);`);
   assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};select saved_amount from public.financial_goals where id=${lit(id)};`),'250.50');
   assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};select count(*) from public.financial_goals where id=${lit(id)};`),'0');
   fail(()=>sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};insert into public.financial_goals(user_id,name,target_amount) values(${lit(A)},'Forged',500);`),/row-level security/);
 });
 await test('goal archive restores and invalid target is rejected',()=>{
   const id=randomUUID();sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};insert into public.financial_goals(id,user_id,name,target_amount) values(${lit(id)},${lit(A)},'Fund',100);update public.financial_goals set archived=true where id=${lit(id)};update public.financial_goals set archived=false where id=${lit(id)};`);
   assert.equal(sql(`select archived from public.financial_goals where id=${lit(id)};`),'f');
   fail(()=>sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};update public.financial_goals set target_amount=0 where id=${lit(id)};`),/check constraint/);
   fail(()=>sql('set role anon;select * from public.financial_goals;'),/permission denied/);
 });
 await test('optimized settings policy preserves owner isolation and rejects forged owner',()=>{
   sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};insert into public.user_settings(user_id,starting_balance) values(${lit(A)},100);`);
   assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};select count(*) from public.user_settings;`),'0');
   fail(()=>sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};insert into public.user_settings(user_id,starting_balance) values(${lit(A)},999);`),/row-level security/);
   assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};select starting_balance from public.user_settings;`),'100');
 });
 await test('regular plus extra payment commits exact principal and linked rows',()=>{const id=loan();const r=call(randomUUID(),'record',record(id,30));assert.equal(balance(id),4820);assert.equal(r.total_paid,230);assert.equal(r.principal,180);assert.equal(count(),3);assert(r.transactions.filter(x=>x.type==='expense').every(x=>x.loan_id===id));});
 await test('extra-only and payoff never record more than remaining principal',()=>{const id=loan(100);const r=call(randomUUID(),'record',record(id,500,false));assert.equal(balance(id),0);assert.equal(r.total_paid,100);assert.equal(count(),2);fail(()=>call(randomUUID(),'record',record(id)),/already paid off/);assert.equal(count(),2);});
 await test('regular payoff caps amount including interest',()=>{const id=loan(100);const r=call(randomUUID(),'record',record(id));assert.equal(r.total_paid,101);assert.equal(balance(id),0);assert.equal(r.principal,100);});
 await test('retry does not duplicate and returns current snapshot',()=>{const id=loan(),op=randomUUID(),p=record(id);const a=call(op,'record',p);call(randomUUID(),'record',record(id,50,false));const b=call(op,'record',p);assert.equal(count(),3);assert.equal(b.replayed,true);assert.equal(b.total_paid,a.total_paid);assert.equal(b.transactions.find(t=>t.id===id).balance,4800);});
 await test('operation key rejects changed inputs',()=>{const id=loan(),op=randomUUID();call(op,'record',record(id));fail(()=>call(op,'record',record(id,10)),/different request/);assert.equal(balance(id),4850);});
 await test('insert failure rolls back payment rows, balance and receipt',()=>{const id=loan(),op=randomUUID();sql(`create function public.fail_extra() returns trigger language plpgsql as $$ begin if new.description like '% extra payment' then raise exception 'injected extra insert failure'; end if; return new; end; $$;create trigger fail_extra before insert on public.transactions for each row execute function public.fail_extra();`);try{fail(()=>call(op,'record',record(id,30)),/injected extra/);assert.equal(balance(id),5000);assert.equal(count(),1);assert.equal(receipts(),0);}finally{sql('drop trigger fail_extra on public.transactions;drop function public.fail_extra();');}call(op,'record',record(id,30));assert.equal(balance(id),4820);});
 await test('cross-account record and delete cannot affect other owner',()=>{const id=loan(5000,12,200,B);fail(()=>call(randomUUID(),'record',record(id)),/Loan not found/);fail(()=>call(randomUUID(),'delete',{id}),/Transaction not found/);assert.equal(balance(id),5000);assert.equal(receipts(),0);});
 await test('unauthenticated and anonymous calls are denied',()=>{const id=loan();fail(()=>call(randomUUID(),'record',record(id),null),/Sign in/);fail(()=>call(randomUUID(),'record',record(id),A,'anon'),/permission denied/);assert.equal(balance(id),5000);});
 await test('private receipts cannot be read or forged by authenticated role',()=>{fail(()=>sql('set role authenticated; select * from finpulse_private.operations;'),/permission denied/);fail(()=>sql(`set role authenticated;insert into finpulse_private.operations(user_id,operation_id,kind,request) values(${lit(A)},${lit(randomUUID())},'delete','{}');`),/permission denied/);});
 await test('response contains only owner transactions',()=>{const id=loan();loan(7000,12,200,B);const r=call(randomUUID(),'record',record(id));assert(r.transactions.every(t=>t.user_id===A));assert.equal(r.transactions.length,2);});
 await test('delete and undo restore exact principal and original ID',()=>{const id=loan();call(randomUUID(),'record',record(id,30));const pay=sql(`select id from public.transactions where description='Test Car Loan payment'`),del=randomUUID();const d=call(del,'delete',{id:pay});assert.equal(d.restore_info.amount,150);assert.equal(balance(id),4970);assert.equal(count(),2);const undo=randomUUID();call(undo,'undo',{delete_operation_id:del});assert.equal(balance(id),4820);assert.equal(sql(`select id from public.transactions where id=${lit(pay)}`),pay);call(undo,'undo',{delete_operation_id:del});assert.equal(balance(id),4820);assert.equal(count(),3);fail(()=>call(randomUUID(),'undo',{delete_operation_id:del}),/already undone/);});
 await test('delete failure rolls back balance and receipt',()=>{const id=loan();call(randomUUID(),'record',record(id));const pay=sql(`select id from public.transactions where type='expense'`);sql(`create function public.fail_delete() returns trigger language plpgsql as $$begin raise exception 'injected delete failure';end;$$;create trigger fail_delete before delete on public.transactions for each row execute function public.fail_delete();`);try{fail(()=>call(randomUUID(),'delete',{id:pay}),/injected delete/);assert.equal(balance(id),4850);assert.equal(count(),2);assert.equal(receipts(),1);}finally{sql('drop trigger fail_delete on public.transactions;drop function public.fail_delete();');}});
 await test('undo failure rolls back balance and undone marker',()=>{const id=loan();call(randomUUID(),'record',record(id));const pay=sql(`select id from public.transactions where type='expense'`),del=randomUUID();call(del,'delete',{id:pay});sql(`create function public.fail_restore() returns trigger language plpgsql as $$begin if new.type='expense' then raise exception 'injected restore failure';end if;return new;end;$$;create trigger fail_restore before insert on public.transactions for each row execute function public.fail_restore();`);try{fail(()=>call(randomUUID(),'undo',{delete_operation_id:del}),/injected restore/);assert.equal(balance(id),5000);assert.equal(count(),1);assert.equal(sql(`select undone_by is null from finpulse_private.operations where operation_id=${lit(del)}`),'t');}finally{sql('drop trigger fail_restore on public.transactions;drop function public.fail_restore();');}call(randomUUID(),'undo',{delete_operation_id:del});assert.equal(balance(id),4850);});
 await test('loan undo preserves ID and existing payment links',()=>{const id=loan();call(randomUUID(),'record',record(id));const del=randomUUID();call(del,'delete',{id});call(randomUUID(),'undo',{delete_operation_id:del});assert.equal(sql(`select id from public.transactions where type='loan'`),id);assert.equal(sql(`select loan_id from public.transactions where type='expense'`),id);});
 await test('legacy regular payment retains documented interest estimate',()=>{const id=loan(),pay=randomUUID();sql(`insert into public.transactions(id,user_id,type,description,amount,date,category)values(${lit(pay)},${lit(A)},'expense','Test Car Loan payment',200,'2026-09-10','loan_payment');`);const r=call(randomUUID(),'delete',{id:pay});assert.equal(r.restore_info.amount,150);assert.equal(r.restore_info.estimated,true);assert.equal(balance(id),5150);});
 await test('ambiguous legacy matching fails without changing data',()=>{loan();loan();const pay=randomUUID();sql(`insert into public.transactions(id,user_id,type,description,amount,date,category)values(${lit(pay)},${lit(A)},'expense','Test Car Loan payment',200,'2026-09-10','loan_payment');`);fail(()=>call(randomUUID(),'delete',{id:pay}),/multiple loans/);assert.equal(count(),3);assert.equal(receipts(),0);});
 await test('missing transaction and foreign deletion receipt are denied',()=>{const id=loan(100,0,100,B),del=randomUUID();call(del,'delete',{id},B);fail(()=>call(randomUUID(),'undo',{delete_operation_id:del}),/Deletion not found/);fail(()=>call(randomUUID(),'delete',{id:randomUUID()}),/Transaction not found/);});
 await test('invalid payment inputs roll back receipt',()=>{const id=loan();for(const extra of [-1,'NaN','Infinity',1e15])fail(()=>call(randomUUID(),'record',record(id,extra)),/Invalid payment inputs/);fail(()=>call(randomUUID(),'record',{...record(id),date:'2026-02-31'}),/out of range/);assert.equal(balance(id),5000);assert.equal(receipts(),0);});
 await test('simultaneous retries apply one payment',async()=>{const id=loan(),op=randomUUID(),p=record(id);const r=await Promise.all(Array.from({length:8},()=>asyncSql(query(op,'record',p))));assert.equal(balance(id),4850);assert.equal(count(),2);assert.equal(receipts(),1);assert.equal(r.map(JSON.parse).filter(x=>!x.replayed).length,1);});
 await test('simultaneous distinct payments use latest balance',async()=>{const id=loan(100,0,10);await Promise.all(Array.from({length:8},()=>asyncSql(query(randomUUID(),'record',record(id,10,false)))));assert.equal(balance(id),20);assert.equal(count(),9);});
 await test('simultaneous deletes restore principal once',async()=>{const id=loan();call(randomUUID(),'record',record(id));const pay=sql(`select id from public.transactions where type='expense'`);const r=await Promise.allSettled(Array.from({length:4},()=>asyncSql(query(randomUUID(),'delete',{id:pay}))));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(balance(id),5000);assert.equal(count(),1);});
 await test('stale undo cannot reduce balance below zero',()=>{const id=loan();call(randomUUID(),'record',record(id));const pay=sql(`select id from public.transactions where type='expense'`),del=randomUUID();call(del,'delete',{id:pay});sql(`update public.transactions set balance=0 where id=${lit(id)}`);fail(()=>call(randomUUID(),'undo',{delete_operation_id:del}),/balance changed/);assert.equal(balance(id),0);assert.equal(count(),1);});
 await test('deleting a payment from zero balance restores only principal and undo returns zero',()=>{const id=loan(0),pay=randomUUID(),del=randomUUID();sql(`insert into public.transactions(id,user_id,type,description,amount,date,category,principal_applied,loan_id) values(${lit(pay)},${lit(A)},'expense','Test Car Loan payment',90,'2026-10-10','loan_payment',80,${lit(id)});`);call(del,'delete',{id:pay});assert.equal(balance(id),80);call(randomUUID(),'undo',{delete_operation_id:del});assert.equal(balance(id),0);});
 await test('payment linked to foreign loan cannot restore foreign debt',()=>{const id=loan(5000,12,200,B),pay=randomUUID();sql(`insert into public.transactions(id,user_id,type,description,amount,date,category,principal_applied,loan_id) values(${lit(pay)},${lit(A)},'expense','Payment',100,'2026-10-10','loan_payment',100,${lit(id)});`);const r=call(randomUUID(),'delete',{id:pay});assert.equal(r.restore_info,null);assert.equal(balance(id),5000);});
 await test('operation UUID is scoped to each owner',()=>{const a=loan(),b=loan(5000,12,200,B),op=randomUUID();call(op,'record',record(a));call(op,'record',record(b),B);assert.equal(balance(a),4850);assert.equal(balance(b),4850);assert.equal(receipts(),2);});
 await test('API wrapper is invoker, private definer has empty path and receipts use RLS',()=>{assert.equal(sql(`select prosecdef from pg_proc where oid='public.fp_mutate_transaction(uuid,text,jsonb)'::regprocedure`),'f');assert.equal(sql(`select prosecdef from pg_proc where oid='finpulse_private.mutate(uuid,text,jsonb)'::regprocedure`),'t');assert(sql(`select proconfig::text from pg_proc where oid='finpulse_private.mutate(uuid,text,jsonb)'::regprocedure`).includes('search_path'));assert.equal(sql(`select relrowsecurity from pg_class where oid='finpulse_private.operations'::regclass`),'t');assert.equal(sql(`select has_function_privilege('anon','public.fp_mutate_transaction(uuid,text,jsonb)','execute')`),'f');});
 const bill=(actor=A)=>{const id=loan(100,0,10,actor);sql(`update public.transactions set type='bill' where id=${lit(id)}`);return id};
 const mark=(id,paid=true,actor=A,owner=actor)=>sql(`set role authenticated;set request.jwt.claim.sub=${lit(actor)};insert into public.bill_paid_marks(user_id,bill_id,due_date,paid,marked_at)values(${lit(owner)},${lit(id)},'2026-10-10',${paid},'2026-10-09')on conflict(user_id,bill_id,due_date)do update set paid=excluded.paid,marked_at=excluded.marked_at returning paid;`);
 await test('bill status persists for another session of the same owner',()=>{const id=bill();assert.equal(mark(id),'t');assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};select count(*) from public.bill_paid_marks`),'1');});
 await test('bill unmark retains false tombstone and never changes financial rows',()=>{const id=bill();mark(id);assert.equal(mark(id,false),'f');assert.equal(balance(id),100);assert.equal(count(),1);assert.equal(sql('select count(*) from public.bill_paid_marks'),'1');});
 await test('bill marks deny foreign bill ownership and forged user ID',()=>{const id=bill(B);fail(()=>mark(id),/row-level security/);fail(()=>mark(id,true,A,B),/row-level security/);assert.equal(sql('select count(*) from public.bill_paid_marks'),'0');});
 await test('bill marks cannot be created for loans or one-time expenses',()=>{const id=loan();fail(()=>mark(id),/row-level security/);sql(`update public.transactions set type='expense',recurring=false where id=${lit(id)}`);fail(()=>mark(id),/row-level security/);});
 await test('bill marks owner read isolation and foreign update denial',()=>{const id=bill();mark(id);assert.equal(sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};select count(*) from public.bill_paid_marks`),'0');sql(`set role authenticated;set request.jwt.claim.sub=${lit(B)};update public.bill_paid_marks set paid=false`);assert.equal(sql('select paid from public.bill_paid_marks'),'t');});
 await test('bill marks anonymous access and direct deletion are denied',()=>{const id=bill();mark(id);fail(()=>sql('set role anon;select * from public.bill_paid_marks'),/permission denied/);fail(()=>sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};delete from public.bill_paid_marks`),/permission denied/);});
 await test('legacy sync cannot overwrite account unmark',()=>{const id=bill();mark(id,false);sql(`set role authenticated;set request.jwt.claim.sub=${lit(A)};insert into public.bill_paid_marks values(${lit(A)},${lit(id)},'2026-10-10',true,'2026-10-09')on conflict(user_id,bill_id,due_date)do nothing`);assert.equal(sql('select paid from public.bill_paid_marks'),'f');});
 await test('deleting a bill cascades only its own marks',()=>{const a=bill(),b=bill();mark(a);mark(b);sql(`delete from public.transactions where id=${lit(a)}`);assert.equal(sql('select count(*) from public.bill_paid_marks'),'1');assert.equal(sql('select bill_id from public.bill_paid_marks'),b);});
 console.log(`DATABASE TOTAL pass=${pass} fail=${failed}`);process.exitCode=failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
